-- Colorscheme for lualine

local colors = {
	none = "NONE",
	fg = "#E1E1E1",
	bg = "#151515",
	alt_bg = "#171717",
	accent = "#202020",
	white = "#E1E1E1",
	gray = "#373737",
	medium_gray = "#727272",
	light_gray = "#AFAFAF",
	blue = "#A5D6FF",
	gray_blue = "#7E97AB",
	medium_gray_blue = "#A2B5C1",
	cyan = "#88afa2",
	red = "#CC6666",
	green = "#90A959",
	light_green = "#90A959",
	yellow = "#F4BF75",
	orange = "#FFA557",
	purple = "#AA749F",
	pale_purple = "#A5D6FF",
	magenta = "#AA759F",
	cursor_fg = "#D0D0D0",
	cursor_bg = "#151515",
	sign_add = "#90A959",
	sign_change = "#82a8c8",
	sign_delete = "#AC4142",
	error = "#AC4142",
	warning = "#F4BF75",
	info = "#F4BF75",
	hint = "#A5D6FF",
	hint_green = "#90A959",
	neogit_light_green = "#4f5c32",
	neogit_blue = "#33424f",
	neogit_green = "#3f4928",
	neogit_light_red = "#4f2929",
	neogit_red = "#3f2121",
	purple_test = "#ff00ff",
	cyan_test = "#00ffff",
}

return {
	normal = {
		a = { fg = colors.fg, bg = colors.red, gui = "bold" },
		b = { fg = colors.fg, bg = colors.bg },
		c = { fg = colors.fg, bg = colors.bg },
	},
	insert = { a = { fg = colors.fg, bg = colors.bg, gui = "bold" } },
	visual = { a = { fg = colors.fg, bg = colors.bg, gui = "bold" } },
	command = { a = { fg = colors.fg, bg = colors.bg, gui = "bold" } },
	replace = { a = { fg = colors.fg, bg = colors.bg, gui = "bold" } },
	inactive = {
		a = { fg = colors.fg, bg = colors.bg },
		b = { fg = colors.fg, bg = colors.bg },
		c = { fg = colors.fg, bg = colors.bg },
	},
}
